### PR TITLE
Created faq page with collapsible feature for each qn

### PR DESCRIPTION
**Pull request by takeachangs**
Styling requires attention next week

### CODE REVIEW

**Comment by Ram-Raghav-S** [comment]
Hey Seongmin, I haven't taken a look at how it looks yet, but I noticed that there are a few repeated files and folders added as part of the PR.
 image
Is this possibly something that got messed up while commiting?

**Comment by takeachangs** [comment]
> Hey Seongmin, I haven't taken a look at how it looks yet, but I noticed that there are a few repeated files and folders added as part of the PR. image Is this possibly something that got messed up while commiting?

hey Ram i've installed a few more npm packages and those files are the new packages

**Review by PierreLessard — APPROVED** [review]
Fixed the unneeded files and some styling so it looks good to go now. Good job Seongmin!

**Review by Ram-Raghav-S — APPROVED** [review]
Looks good.

**Pull request merged**
